[package]
name = "alacrity"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]

log = "0.3"
env_logger = "0.3.1"
futures = "0.1.1"
tokio-core = "0.1.0"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }

[[bin]]
name = "alacrity"
path = "src/main.rs"

[[bin]]
name = "test-server"
path = "src/test-server.rs"
