[package]
name = "alacrity"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]

log = "0.3"
env_logger = "0.3.1"
futures = { git = "https://github.com/alexcrichton/futures-rs" }
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }

[[bin]]
name = "alacrity"
path = "src/main.rs"

[[bin]]
name = "test-server"
path = "src/test-server.rs"
