[package]
name = "alacrity"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]

log = "0.3"
env_logger = "0.3.1"
futures = "0.1.1"
tokio-core = "0.1.0"
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
bytes = { git = "https://github.com/carllerche/bytes" }
nom = "1.2.4"

rustful = "0.9"

[dev-dependencies]
hyper = "0.9"

[[bin]]
name = "alacrity"
path = "src/alacrity.rs"

[[bin]]
name = "test-server"
path = "src/test-server.rs"
