[package]
name = "alacrity"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]

log = "0.3"
env_logger = "0.3.1"
futures = "0.1.1"
hyper = { git = "https://github.com/hyperium/hyper" }
tokio-core = "0.1"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
tokio-timer = "0.1.0"

rustc-serialize = "0.3.19"

[dependencies.rustful]
version = "0.9"
default-features = false
features = ["rustc_json_body"]

[dev-dependencies]
reqwest = "0.2.0"

[[bin]]
name = "alacrity"
path = "src/alacrity.rs"

[[bin]]
name = "test-server"
path = "src/test-server.rs"
